### PR TITLE
remove builddeps from docker container

### PR DESCRIPTION
**Pull request by foosinn**
removing the build only packages makes the docker container a lot smaller.

### CODE REVIEW

**Comment by foosinn** [comment]
image size is now down to 13M
foosinn/biboumi

**Comment by louiz** [comment]
I like this idea, thank you very much.

Wouldn’t it be better and cleaner to use this feature, though : https://docs.docker.com/develop/develop-images/multistage-build/ ?
Especially to avoid the “combine runs into just one big run, just to make things lighter, even though it makes the file a lot messier”.

**Comment by louiz** [comment]
What a timing, I was just starting a 18.05 docker server to try to do this multi-stage build by myself on my test machine. Now that you did it, I’ll just test it right now, thanks. :)

**Comment by foosinn** [comment]
:+1: 

i'm just wondering if it would more sense to build a static binary and drop the alpine packages completely?

**Comment by louiz** [comment]
> i'm just wondering if it would more sense to build a static binary and drop the alpine packages completely?

We could, but I think the current state is just fine as it is. No need to make things more “complex”.

By the way, github doesn’t provide a way to merge this pull request but squash everything in one commit? Could you please squash everything and force pull on your branch? I’ll merge it.

**Pull request closed without merging**
